#!/bin/bash

if [[ "$#" -lt 1 ]]; then
  echo "Usage: $0 [<env-file>|local] [--auto]"
  echo ""
  exit 1
elif [[ "$1" != "local" ]] && [[ ! -f "$1" ]]; then
  echo "ABORTING: specified env-file not found: $1"
  exit 1
else
  if [[ "$1" = "local" ]]; then
    export AWS_DYNAMODB_ACCESS_KEY=""
    export AWS_DYNAMODB_SECRET_KEY=""
    export AWS_DYNAMODB_ENDPOINT="http://localhost:6798"
  else
    echo "Using $1 for IAM creds..."
    source $1
  fi

  if [[ "$2" = "--auto" ]]; then
    lein test-auto
  else
    lein test-all
  fi
fi
